defaultSessions = 3

[focus]
uri = "spotify:playlist:0vvXsWCC9xrXsKd4FyS8kM"
volume = 55
defaultDuration = 20

[rest]
uri = "spotify:track:7HrE6HtYNBbGqp5GmHbFV0"
volume = 55
defaultDuration = 1

[done]
volume = 40
